[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
lifecycleProcess = "2.9.4"
androidx-testExt = "1.3.0"
composeHotReload = "1.0.0-rc02"
composeMultiplatform = "1.9.1"
junit = "4.13.2"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
kotlinx-collections-immutable = "0.4.0"
dataStore = "1.1.7"
atomicfu = "0.29.0"
kotlinDate = "0.7.1"
ksp = "2.2.10-2.0.2"
kotlinSerialization = "1.9.0"
navigationCompose = "2.9.1"
koin = "4.1.1"
koinComposeMultiplatform = "4.1.1"
okioVersion = "3.16.0"
fileKitVersion = "0.12.0"
zip4j = "2.11.5"
kotlinStdlib = "2.2.20"
runner = "1.7.0"
core = "1.7.0"
cryptography-kotlin = "0.5.0"
moko-biometry = "0.4.0"
mokkery = "2.10.2"
kmLogging = "2.1.0"
firebase = "2.1.0"
log4j = "2.0.9"
revenuecatKmp = "2.2.13+17.23.0"
revenuecatAndroid = "9.15.3"
purchases-common = "17.23.0"
playReview = "2.0.2"
googleServices = "4.4.2"
plugin-crashlitics = "3.0.2"
jna = "5.16.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "dataStore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStore" }

kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-date = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDate" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

logging = { module = "com.diamondedge:logging", version.ref = "kmLogging" }
log4j = { module = "org.slf4j:slf4j-simple", version.ref = "log4j" }
firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "firebase" }
firebase-installations = { module = "dev.gitlive:firebase-installations", version.ref = "firebase" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-jvm = { module = "io.insert-koin:koin-core-jvm", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeMultiplatform" }

okio = { module = "com.squareup.okio:okio", version.ref = "okioVersion" }
filekit = { module = "io.github.vinceglb:filekit-core", version.ref = "fileKitVersion" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "fileKitVersion" }

zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }

# Cryptography - RNCryptor KMP implementation
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptography-kotlin" }
cryptography-provider = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal", version.ref = "cryptography-kotlin" }

# Biometry - Biometric authentication
moko-biometry = { module = "dev.icerock.moko:biometry", version.ref = "moko-biometry" }
moko-biometry-compose = { module = "dev.icerock.moko:biometry-compose", version.ref = "moko-biometry" }

# RevenueCat
revenuecat-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "revenuecatKmp" }
revenuecat-either = { module = "com.revenuecat.purchases:purchases-kmp-either", version.ref = "revenuecatKmp" }
revenuecat-result = { module = "com.revenuecat.purchases:purchases-kmp-result", version.ref = "revenuecatKmp" }
revenuecat-ui = { module = "com.revenuecat.purchases:purchases-kmp-ui", version.ref = "revenuecatKmp" }
revenuecat-android = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecatAndroid" }
revenuecat-android-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "revenuecatAndroid" }

# JNA for native bridge access
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "plugin-crashlitics" }
androidLint = { id = "com.android.lint", version.ref = "agp" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }